/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fi_tut_cloud_arvue_resource_ResourceInfo */

#ifndef _Included_fi_tut_cloud_arvue_resource_ResourceInfo
#define _Included_fi_tut_cloud_arvue_resource_ResourceInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fi_tut_cloud_arvue_resource_ResourceInfo
 * Method:    update
 * Signature: (Ljava/lang/ThreadGroup;)V
 */
JNIEXPORT void JNICALL Java_fi_tut_cloud_arvue_resource_ResourceInfo_update
  (JNIEnv *, jobject, jobject);

/*
 * Class:     fi_tut_cloud_arvue_resource_ResourceInfo
 * Method:    getAll
 * Signature: ()[Lfi/tut/cloud/arvue/resource/ResourceInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_fi_tut_cloud_arvue_resource_ResourceInfo_getAll
  (JNIEnv *, jclass);

/*
 * Class:     fi_tut_cloud_arvue_resource_ResourceInfo
 * Method:    gc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fi_tut_cloud_arvue_resource_ResourceInfo_gc
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
